# Default values for tfjob.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

useHostNetwork: false
useHostPID: true
useHostIPC: true
gpuCount: 0 # user define
privileged: false

chief: 0
# Possible value: Chief/Master
chiefName: Chief
# chiefPort: 2221
chiefAnnotations: {}
# chiefAnnotations:

workers: 1
workerImage: kubeflow/tf-dist-mnist-test:1.0
# workerCpu: 1
# workerMemory: 1 Gi
# workPort: 2222

ps: 0
psImage: kubeflow/tf-dist-mnist-test:1.0
# psCpu: 1
# psMemory: 1 Gi
# psPort: 2223
annotations: {}

evaluator: 0
evaluatorImage: kubeflow/tf-dist-mnist-test:1.0
evaluatorAnnotations: {}

# rsync image
rsyncImage: registry.cn-zhangjiakou.aliyuncs.com/tensorflow-samples/rsync
# git sync image
gitImage: registry.cn-zhangjiakou.aliyuncs.com/tensorflow-samples/git-sync:v2.0.6

imagePullPolicy: Always

useTensorboard: false
tensorboardImage: registry.cn-zhangjiakou.aliyuncs.com/tensorflow-samples/tensorflow:1.5.0-devel
tensorboardImagePullpolicy: Always
tensorboardServiceType: NodePort

trainingLogdir: /output/training_logs

# disable by default 
binpack: false

# enable gang scheduler
enableGangScheduler: false
schedulerName: kube-batchd

# enable RDMA support
enableRDMA: false

# hostLogPath: /training_logs/112345_logs

# nvidiaPath: /usr/local/nvidia-docker/nvidia_driver/384.81
