---
kind: Namespace
apiVersion: v1
metadata:
  name: arena-system
  labels:
    name: arena-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobmon
  namespace: arena-system

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jobmon
subjects:
  - kind: ServiceAccount
    name: jobmon
    namespace: arena-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io